apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  selector:
    app: hello-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP