apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/prince-reg:ps-radeon
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          value: "production"
        # MongoDB URL will be set at runtime
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URL
