apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  selector:
    app: profile-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP